<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2017/01/11 18:55:40

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;port=3306;dbname=hensonhrm_mysql',
  'username' => 'root',
  'password' => NULL,
  'attributes' => 
  array (
    'export' => 'tables',
  ),
  'name' => 'doctrine',
)),);
